version: 1.4.{build}
os: Visual Studio 2017
platform: x64

environment:
  VCPKG_DEFAULT_TRIPLET: x64-windows
  GENERATOR: "Visual Studio 14 2015 Win64"

install:
- vcpkg install pmdk:x64-windows
- vcpkg install sfml:x64-windows
- vcpkg integrate install

cache: c:\tools\vcpkg\installed

configuration:
- Debug
- Release

matrix:
  fast_finish: true

before_build:
- cmake . -Bbuild -G "%GENERATOR%"
        -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
        -DCMAKE_INSTALL_PREFIX=c:/install/libpmemobj-cpp
        -DTESTS_USE_FORCED_PMEM=ON

build_script:
- msbuild build/ALL_BUILD.vcxproj /property:Configuration=%CONFIGURATION%
          /verbosity:minimal

test_script:
- cd build
- ctest -C %CONFIGURATION% --output-on-failure --timeout 540
- msbuild INSTALL.vcxproj /verbosity:minimal
- cd ..
# build standalone example
- cd examples/map_cli
- cmake . -G "%GENERATOR%"
        -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
        -DCMAKE_PREFIX_PATH=c:/install/libpmemobj-cpp
        -DTESTS_USE_FORCED_PMEM=ON
- msbuild ALL_BUILD.vcxproj /verbosity:minimal
